(part "MJTP1117"
    (packageRef "MJTP1117")
    (interface
        (port "1" (symbPinId 1) (portName "COM") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NO") (portType INOUT))
        (port "3" (symbPinId 3) (portName "MH1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Manufacturer_Name" "Apem")
    (property "Manufacturer_Part_Number" "MJTP1117")
    (property "Mouser_Part_Number" "642-MJTP1117")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Apem/MJTP1117?qs=6hR9CYnVCPAeQNDPI%2FtCng%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "APEM - MJTP1117 - TACTILE SW, SPST, 0.05A, 12VDC, TH")
    (property "Datasheet_Link" "https://mm.digikey.com/Volume0/opasdata/d220001/medias/docus/5561/MJTP%20thruhole.pdf")
    (property "symbolName1" "MJTP1117")
)
