(part "MPM3810GQB-33-Z"
    (packageRef "MPM3810GQB33Z")
    (interface
        (port "1" (symbPinId 1) (portName "PGND_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "PGND_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VIN") (portType INOUT))
        (port "8" (symbPinId 8) (portName "PG") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EN") (portType INOUT))
        (port "10" (symbPinId 10) (portName "NC_3") (portType INOUT))
        (port "11" (symbPinId 11) (portName "AGND") (portType INOUT))
        (port "12" (symbPinId 12) (portName "OUT_S") (portType INOUT))
        (port "13" (symbPinId 13) (portName "NC_4") (portType INOUT))
        (port "14" (symbPinId 14) (portName "OUT_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "946-MPM3810GQB-33-Z")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Monolithic-Power-Systems-MPS/MPM3810GQB-33-Z?qs=WskeALMjHsooCNVHuZWMUQ%3D%3D")
    (property "Manufacturer_Name" "Monolithic Power Systems (MPS)")
    (property "Manufacturer_Part_Number" "MPM3810GQB-33-Z")
    (property "Description" "Switching Voltage Regulators 6V Input 3.3V Output 4Mhz, 1A Step-Down")
    (property "Datasheet_Link" "https://www.monolithicpower.com/pub/media/document/MPM3810_r1.1.pdf")
    (property "symbolName1" "MPM3810GQB-33-Z")
)
